#!/bin/bash
echo "========== SYSTEM HEALTH CHECK =========="
echo "Date: $(date)"
echo "Hostname: $(hostname)"
echo ""
echo "--- OS Info ---"
cat /etc/os-release | grep -E "NAME|VERSION"
echo ""
echo "--- CPU Usage ---"
top -bn1 | grep "Cpu(s)" | awk '{print "CPU Usage: " $2"%"}'
echo ""
echo "--- Memory Usage ---"
free -h | awk '/^Mem:/ {print "Total: "$2" | Used: "$3" | Free: "$4}'
echo ""
echo "--- Disk Usage ---"
df -h / | awk 'NR==2 {print "Total: "$2" | Used: "$3" | Available: "$4" | Use%: "$5}'
echo ""
echo "--- Running Services ---"
systemctl is-active amazon-cloudwatch-agent && echo "CloudWatch Agent: RUNNING" || echo "CloudWatch Agent: STOPPED"
systemctl is-active snap.amazon-ssm-agent.amazon-ssm-agent && echo "SSM Agent: RUNNING" || echo "SSM Agent: STOPPED"
echo ""
echo "--- Network Connectivity ---"
curl -s --max-time 5 https://aws.amazon.com > /dev/null && echo "Internet: REACHABLE" || echo "Internet: UNREACHABLE"
curl -s --max-time 5 https://ssm.ap-south-1.amazonaws.com > /dev/null && echo "SSM Endpoint: REACHABLE" || echo "SSM Endpoint: UNREACHABLE"
echo ""
echo "--- Flask App Status ---"
curl -s http://localhost:80/health || echo "Flask App: NOT RUNNING"
echo ""
echo "=========================================="